settings:
    max_sub_nodes: 0
    max_tree_depth: 0
    prob_depending: false
    rolow: 5.0
    roupp: 20
    smoothing_function: cos(ax+b)
structure:
    0:
        A:
            0:
                - [1, 0]
                - [0, 1]
            1:
                - [1.0, 0.1]
                - [-0.1, 1.0]
            2:
                - [1.0, 0.1]
                - [-0.1, 1.0]
            3:
                - [1.0, -0.1]
                - [0.1, 1.0]
            4:
                - [1.0, 0.1]
                - [-0.1, 1.0]
        B:
            0:
                - [1, 0]
                - [0, 1]
            1:
                - [1, 0]
                - [0, 1]
            2:
                - [1, 0]
                - [0, 1]
            3:
                - [1.0, 0.1]
                - [-0.1, 1.0]
            4:
                - [1, 0]
                - [0, 1]
        controls:
            0: [0.0, 0.0]
            1: [0.0, 0.0]
            2: [0.0, 0.0]
            3: [0.0, 0.0]
            4: [0.0, 0.0]
        coordinates:
            0: [0.0, 0.0]
            1: [5.0, 0.0]
            2: [0.0, 5.0]
            3: [-5.0, 0.0]
            4: [0.0, -5.0]
    1:
        controls:
            0: [-1.0, -1.0]
            1: [0.0, 0.0]
            2: [0.0, 0.0]
            3: [0.0, 0.0]
            4: [0.0, 0.0]
    2:
        controls:
            0: [-0.7, -1.6]
            1: [0.0, 0.0]
            2: [0.0, 0.0]
            3: [0.0, 0.0]
            4: [0.0, 0.0]
    3:
        controls:
            0: [1.0, -2.0]
            1: [0.0, 0.0]
            2: [0.0, 0.0]
            3: [0.0, 0.0]
            4: [0.0, 0.0]
    4:
        controls:
            0: [0.0, -1.0]
            1: [0.0, 0.0]
            2: [0.0, 0.0]
            3: [0.0, 0.0]
            4: [0.0, 0.0]
    5:
        controls:
            0: [0.0, -1.0]
            1: [0.0, 0.0]
            2: [0.0, 0.0]
            3: [0.0, 0.0]
            4: [0.0, 0.0]
    6:
        controls:
            0: [-0.5, -0.1]
            1: [0.0, 0.0]
            2: [0.0, 0.0]
            3: [0.0, 0.0]
            4: [0.0, 0.0]
    7:
        controls:
            0: [-1.0, -0.5]
            1: [0.0, 0.0]
            2: [0.0, 0.0]
            3: [0.0, 0.0]
            4: [0.0, 0.0]
    8:
        controls:
            0: [-1.0, -0.5]
            1: [0.0, 0.0]
            2: [0.0, 0.0]
            3: [0.0, 0.0]
            4: [0.0, 0.0]
    9:
        controls:
            0: [-1.0, -0.9]
            1: [0.0, 0.0]
            2: [0.0, 0.0]
            3: [0.0, 0.0]
            4: [0.0, 0.0]
    10:
        controls:
            0: [0.0, -1.0]
            1: [0.0, 0.0]
            2: [0.0, 0.0]
            3: [0.0, 0.0]
            4: [0.0, 0.0]
    11:
        controls:
            0: [0.0, -1.0]
            1: [0.0, 0.0]
            2: [0.0, 0.0]
            3: [0.0, 0.0]
            4: [0.0, 0.0]
    12:
        controls:
            0: [0.0, -1.0]
            1: [0.0, 0.0]
            2: [0.0, 0.0]
            3: [0.0, 0.0]
            4: [0.0, 0.0]
    13:
        controls:
            0: [0.0, -1.0]
            1: [0.0, 0.0]
            2: [0.0, 0.0]
            3: [0.0, 0.0]
            4: [0.0, 0.0]
    14:
        controls:
            0: [0.0, -1.0]
            1: [0.0, 0.0]
            2: [0.0, 0.0]
            3: [0.0, 0.0]
            4: [0.0, 0.0]
    15:
        controls:
            0: [0.0, -1.0]
            1: [0.0, 0.0]
            2: [0.0, 0.0]
            3: [0.0, 0.0]
            4: [0.0, 0.0]
    16:
        controls:
            0: [0.0, -1.0]
            1: [0.0, 0.0]
            2: [0.0, 0.0]
            3: [0.0, 0.0]
            4: [0.0, 0.0]
    17:
        controls:
            0: [0.0, -1.0]
            1: [0.0, 0.0]
            2: [0.0, 0.0]
            3: [0.0, 0.0]
            4: [0.0, 0.0]
    18:
        controls:
            0: [0.5, -1.0]
            1: [0.0, 0.0]
            2: [0.0, 0.0]
            3: [0.0, 0.0]
            4: [0.0, 0.0]
    19:
        controls:
            0: [1.0, -1.0]
            1: [0.0, 0.0]
            2: [0.0, 0.0]
            3: [0.0, 0.0]
            4: [0.0, 0.0]
    20:
        controls:
            0: [1.0, -1.0]
            1: [0.0, 0.0]
            2: [0.0, 0.0]
            3: [0.0, 0.0]
            4: [0.0, 0.0]
    21:
        controls:
            0: [1.0, -1.0]
            1: [0.0, 0.0]
            2: [0.0, 0.0]
            3: [0.0, 0.0]
            4: [0.0, 0.0]
    22:
        controls:
            0: [1.0, -1.0]
            1: [0.0, 0.0]
            2: [0.0, 0.0]
            3: [0.0, 0.0]
            4: [0.0, 0.0]
    23:
        controls:
            0: [1.0, -1.0]
            1: [0.0, 0.0]
            2: [0.0, 0.0]
            3: [0.0, 0.0]
            4: [0.0, 0.0]
    24:
        controls:
            0: [1.0, -1.0]
            1: [0.0, 0.0]
            2: [0.0, 0.0]
            3: [0.0, 0.0]
            4: [0.0, 0.0]
    25:
        controls:
            0: [1.0, -1.0]
            1: [0.0, 0.0]
            2: [0.0, 0.0]
            3: [0.0, 0.0]
            4: [0.0, 0.0]
    26:
        controls:
            0: [1.0, -1.0]
            1: [0.0, 0.0]
            2: [0.0, 0.0]
            3: [0.0, 0.0]
            4: [0.0, 0.0]
    27:
        controls:
            0: [1.5, -1.0]
            1: [0.0, 0.0]
            2: [0.0, 0.0]
            3: [0.0, 0.0]
            4: [0.0, 0.0]
    28:
        controls:
            0: [1.5, -1.0]
            1: [0.0, 0.0]
            2: [0.0, 0.0]
            3: [0.0, 0.0]
            4: [0.0, 0.0]
    29:
        controls:
            0: [1.5, 0.0]
            1: [0.0, 0.0]
            2: [0.0, 0.0]
            3: [0.0, 0.0]
            4: [0.0, 0.0]
    30:
        controls:
            0: [1.5, 0.0]
            1: [0.0, 0.0]
            2: [0.0, 0.0]
            3: [0.0, 0.0]
            4: [0.0, 0.0]
    31:
        controls:
            0: [0.0, 0.0]
            1: [0.0, 0.0]
            2: [0.0, 0.0]
            3: [0.0, 0.0]
            4: [0.0, 0.0]
    32:
        controls:
            0: [0.5, 0.5]
            1: [0.0, 0.0]
            2: [0.0, 0.0]
            3: [0.0, 0.0]
            4: [0.0, 0.0]

