settings:
    max_sub_nodes: 0
    max_tree_depth: 0
    prob_depending: false
    rolow: 5
    roupp: 100
    smoothing_function: exp(b-a)/((x-a)(x-b))
structure:
    0:
        controls:
            0:
            - 0.0
            - 0.0
            1:
            - 0.0
            - 0.0
            2:
            - 0.0
            - 0.0
            3:
            - 0.0
            - 0.0
            4:
            - 0.0
            - 0.0
            5:
            - 0.0
            - 0.0
            6:
            - 0.0
            - 0.0
            7:
            - 0.0
            - 0.0
        coordinates:
            0:
            - 0.0
            - 0.0
            1:
            - 4.0
            - 0.0
            2:
            - 10.0
            - 0.0
            3:
            - 20.0
            - 3.0
            4:
            - 0.0
            - 3.0
            5:
            - 0.0
            - 6.0
            6:
            - 0.0
            - -3.0
            7:
            - -5.0
            - 0.0
    1:
        controls:
            0:
            - 0.0
            - 0.0
            1:
            - 0.0
            - 0.0
            2:
            - 0.0
            - 0.0
            3:
            - 0.0
            - 0.0
            4:
            - 0.0
            - 0.0
            5:
            - 0.0
            - 0.0
            6:
            - 0.0
            - 0.0
            7:
            - 0.0
            - 0.0
        coordinates:
            0:
            - 0.0
            - 0.0
            1:
            - 4.0
            - 0.0
            2:
            - 10.0
            - 0.0
            3:
            - 20.0
            - 3.0
            4:
            - 0.0
            - 3.0
            5:
            - 0.0
            - 6.0
            6:
            - 0.0
            - -3.0
            7:
            - -5.0
            - 0.0
    2:
        controls:
            0:
            - 0.0
            - 0.0
            1:
            - 0.0
            - 0.0
            2:
            - 0.0
            - 0.0
            3:
            - 0.0
            - 0.0
            4:
            - 0.0
            - 0.0
            5:
            - 0.0
            - 0.0
            6:
            - 0.0
            - 0.0
            7:
            - 0.0
            - 0.0
        coordinates:
            0:
            - 0.0
            - 0.0
            1:
            - 4.0
            - 0.0
            2:
            - 10.0
            - 0.0
            3:
            - 20.0
            - 3.0
            4:
            - 0.0
            - 3.0
            5:
            - 0.0
            - 6.0
            6:
            - 0.0
            - -3.0
            7:
            - -5.0
            - 0.0
    3:
        controls:
            0:
            - 0.0
            - 0.0
            1:
            - 0.0
            - 0.0
            2:
            - 0.0
            - 0.0
            3:
            - 0.0
            - 0.0
            4:
            - 0.0
            - 0.0
            5:
            - 0.0
            - 0.0
            6:
            - 0.0
            - 0.0
            7:
            - 0.0
            - 0.0
        coordinates:
            0:
            - 0.0
            - 0.0
            1:
            - 4.0
            - 0.0
            2:
            - 10.0
            - 0.0
            3:
            - 20.0
            - 3.0
            4:
            - 0.0
            - 3.0
            5:
            - 0.0
            - 6.0
            6:
            - 0.0
            - -3.0
            7:
            - -5.0
            - 0.0
    4:
        controls:
            0:
            - 0.0
            - 0.0
            1:
            - 0.0
            - 0.0
            2:
            - 0.0
            - 0.0
            3:
            - 0.0
            - 0.0
            4:
            - 0.0
            - 0.0
            5:
            - 0.0
            - 0.0
            6:
            - 0.0
            - 0.0
            7:
            - 0.0
            - 0.0
        coordinates:
            0:
            - 0.0
            - 0.0
            1:
            - 4.0
            - 0.0
            2:
            - 10.0
            - 0.0
            3:
            - 20.0
            - 3.0
            4:
            - 0.0
            - 3.0
            5:
            - 0.0
            - 6.0
            6:
            - 0.0
            - -3.0
            7:
            - -5.0
            - 0.0
