# Пример файла-конфига 2. Структура из 4 агентов в течение 5 промежутков времени
#
# settings:
#   Здесь мы не задали параметры prob_depending, max_sub_nodes и max_tree_depth -- программа возьмет 
#   их значения по умолчанию
#
# structure
#   1) Добавлена возможность менять матрицы А, В в каждый промежуток времени.
#   2) Особенность 1: не обязательно для каждого промежутка времени задавать поля A, B, coordinates, controls:
#       a) coordinates: если в момент времени t строго не задано coordinates, то программа их посчитает сама,
#                       исходя из А, В и controls
#                       ВАЖНО: это не касается ситуации, когда t == 0 => пользователь обязан задать координаты
#                       в начальный момент времени
#       b) controls: если не задать controls в момент времени t, тогда:
#                        - если t == 0, то controls задастся стандартными значениями (0, 0 для каждого агента)
#                        - если t > 0, то controls не изменится с предыдущего момента времени
#       с) А, В: если не задать м-цы А, В в момент времени t, тогда:
#                    - если t == 0, то А, В зададутся стандартными значениями (диагональная ед. матрица для каждого агента)
#                    - если t > 0, то А, В не изменятся с предыдущего момента времени
#   3) Особенность 2: пока, к сожалению, нужно указывать каждый промежуток времени здесь явно и хотя бы что-то в нем указать 
#                     даже если мы ничего не хотим менять. Это вылечить сложно прямо сейчас, скорее всего придется переписывать
#                     алгоритм того, как из конфига достаются данные
settings:
    rolow: 5
    roupp: 15
    smoothing_function: cos(ax+b)
structure:
    0:
        A:
            0:
            - [1, 0]
            - [0, 1]
            1:
            - [1, 0]
            - [0, 1]
            2:
            - [1, 0]
            - [0, 1]
            3:
            - [1, 0]
            - [0, 1]
        B:
            0:
            - [1, 0]
            - [0, 1]
            1:
            - [1, 0]
            - [0, 1]
            2:
            - [1, 0]
            - [0, 1]
            3:
            - [1, 0]
            - [0, 1]
        coordinates:
            0: [0.0, 0.0]
            1: [3.0, 5.5]
            2: [6.0, 2.4]
            3: [-3.0, -1.1]
        controls:
            0: [1, 1]
            1: [1, 1]
            2: [1, 1]
            3: [1, 1]
    1:
        controls:
            0: [2, 1]
            1: [2, 1]
            2: [1, 2]
            3: [1, 2]   
    2:
        B:
            0:
            - [1, 0]
            - [0, 1]
            1:
            - [1, 0]
            - [0, 1]
            2:
            - [1, 0]
            - [0, 1]
            3:
            - [1, 0]
            - [0, 1]
    3:
        B:
            0:
            - [1, 0]
            - [0, 1]
            1:
            - [1, 0]
            - [0, 1]
            2:
            - [1, 0]
            - [0, 1]
            3:
            - [1, 0]
            - [0, 1]
    3:
        B:
            0:
            - [1, 0]
            - [0, 1]
            1:
            - [1, 0]
            - [0, 1]
            2:
            - [1, 0]
            - [0, 1]
            3:
            - [1, 0]
            - [0, 1]
    4:
        B:
            0:
            - [1, 0]
            - [0, 1]
            1:
            - [1, 0]
            - [0, 1]
            2:
            - [1, 0]
            - [0, 1]
            3:
            - [1, 0]
            - [0, 1]
